# tmux@mbookair
# Options
set -g mode-keys vi
set -g prefix C-z
set -g mouse on
set-option -g focus-events on
set-option -g status-position top
set -g status-justify absolute-centre
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set-option -g default-terminal "tmux-256color"
set-option -as terminal-overrides ",xterm-256color:RGB"

# Vi pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Nord status bar
set -g status-style "bg=default,fg=#D8DEE9"

set -g status-left "#[fg=#88C0D0,bold]#S"
set -g status-right ""

# Inactive windows
set -g window-status-style "fg=#4C566A"
set -g window-status-format " #I:#W "

# Active window
set -g window-status-current-style "fg=#88C0D0,bold"
set -g window-status-current-format " #I:#W "

# Nord pane borders
set -g pane-border-style "fg=#3B4252"
set -g pane-active-border-style "fg=#88C0D0,bold"

# Nord copy mode
set -g mode-style "bg=#4C566A,fg=#E5E9F0"

# Keymaps
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
