#+TITLE: Doom Emacs Configuration
#+AUTHOR: Nicksha Eric
#+EMAIL: nicksha.eric@gmail.com
#+PROPERTY: header-args:emacs-lisp :tangle config.el
#+STARTUP: overview

* Table of Contents :TOC:noexport:
- [[#packages][Packages]]
- [[#basic][Basic]]
  - [[#personal-information][Personal Information]]
  - [[#appearance][Appearance]]
  - [[#editor-settings][Editor Settings]]
- [[#dashboard][Dashboard]]
  - [[#remove-default-widgets][Remove Default Widgets]]
  - [[#custom-footer-messages][Custom Footer Messages]]
- [[#org-mode][Org Mode]]
  - [[#basic-settings][Basic Settings]]
  - [[#org-roam][Org-Roam]]
- [[#keybindings][Keybindings]]
  - [[#org-roam-1][Org-Roam]]
- [[#latex][LaTeX]]
  - [[#pure-latex-files][Pure LaTeX Files]]
  - [[#symbol-prettification][Symbol Prettification]]
  - [[#latex-preview][LaTeX Preview]]

* Packages

All package declarations go here. This tangles to =packages.el=.

#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; packages.el

;; Performance
(package! gcmh)

;; Use tecosaur's org-mode fork for better LaTeX preview
(unpin! org)

(package! org
  :recipe (:host nil
           :repo "https://git.tecosaur.net/mirrors/org-mode.git"
           :remote "mirror"
           :fork (:host nil
                  :repo "https://git.tecosaur.net/tec/org-mode.git"
                  :branch "dev"
                  :remote "tecosaur")
           :files (:defaults "etc")
           :build t
           :pre-build
           (with-temp-file "org-version.el"
             (require 'lisp-mnt)
             (let ((version (with-temp-buffer
                              (insert-file-contents "lisp/org.el")
                              (lm-header "version")))
                   (git-version
                    (string-trim
                     (with-temp-buffer
                       (call-process "git" nil t nil "rev-parse" "--short" "HEAD")
                       (buffer-string)))))
               (insert
                (format "(defun org-release () \"The release version of Org.\" %S)\n" version)
                (format "(defun org-git-version () \"The truncate git commit hash of Org mode.\" %S)\n" git-version)
                "(provide 'org-version)\n"))))
  :pin nil)

(package! org-roam-ui)
#+end_src

* Basic
** Personal Information

#+begin_src emacs-lisp
;;; config.el -*- lexical-binding: t; -*-

(setq user-full-name "Nicksha Eric"
      user-mail-address "nicksha.eric@gmail.com"
      confirm-kill-emacs nil)
#+end_src

** Appearance
*** Theme

#+begin_src emacs-lisp
(setq doom-theme 'doom-gruvbox
      fancy-splash-image "~/tuxfiles/doom/.config/doom/logo.svg")
#+end_src

*** Fonts

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 18)
      doom-variable-pitch-font (font-spec :family "Inter" :size 18)
      doom-big-font (font-spec :family "JetBrainsMono Nerd Font" :size 28))
#+end_src

** Editor Settings
*** Performance

Garbage collection tweaks to make Emacs faster.

#+begin_src emacs-lisp
;; Reduce garbage collection frequency
(setq gc-cons-threshold 200000000)  ; 200MB

;; Use GCMH (Garbage Collector Magic Hack) for better performance
(use-package! gcmh
  :init
  (setq gcmh-idle-delay 5
        gcmh-high-cons-threshold (* 258 1024 1024))  ; 256MB during idle
  :config
  (gcmh-mode 1))
#+end_src

*** Line Numbers

Use relative line numbers for vim-style navigation.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

*** Indent Guides

Don't display indent guides on blank lines.

#+begin_src emacs-lisp
(setq indent-bars-display-on-blank-lines nil)
#+end_src

*** Highlight Current Line

Only highlight the current line in programming modes and dired.

#+begin_src emacs-lisp
(setq global-hl-line-modes '(prog-mode dired-mode))
#+end_src

*** Column Indicator

Show a vertical line at column 80 to help with line length.

#+begin_src emacs-lisp
(setq-default fill-column 80)
(global-display-fill-column-indicator-mode t)
#+end_src

* Dashboard
** Remove Default Widgets

Remove the default shortmenu and footer from the dashboard.

#+begin_src emacs-lisp
(remove-hook! '+doom-dashboard-functions
  #'doom-dashboard-widget-shortmenu
  #'doom-dashboard-widget-footer)
#+end_src

** Custom Footer Messages

Add random custom messages to the dashboard footer.

#+begin_src emacs-lisp
(defcustom my/dashboard-footer-messages
  '("The one true editor, Emacs!"
    "Who the hell uses VIM anyway? Go Evil!"
    "Free as free speech, free as free Beer"
    "Vi Vi Vi, the editor of the beast"
    "Welcome to the church of Emacs"
    "I showed you my source code, pls respond")
  "A list of messages, one of which dashboard chooses to display.")

(add-hook! '+doom-dashboard-functions :append
  (let* ((icon (propertize
                #(" " 0 1 (display (height 1.5)))
                'face `(:foreground ,(doom-color 'magenta))))
         (msg  (nth (random (length my/dashboard-footer-messages))
                    my/dashboard-footer-messages))
         (line (concat icon msg)))
    (insert "\n" (+doom-dashboard--center +doom-dashboard--width line) "\n")))

(setq-hook! '+doom-dashboard-mode-hook
  evil-normal-state-cursor (list nil))
#+end_src

* Org Mode
** Basic Settings

Set the directory where org files are stored.

#+begin_src emacs-lisp
(setq org-directory "~/Org/")
#+end_src

** Org-Roam

Org-roam configuration for linked note-taking.

#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-directory "~/Org/roam/")
  
  ;; Capture templates
  (setq org-roam-capture-templates
        '(("d" "default" plain "%?"
           :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
           :unnarrowed t)
          ("c" "course" plain
           "* Course Info\n- Instructor: \n- Term: \n\n* Week 1\n\n* Assignments\n"
           :target (file+head "courses/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :course:\n")
           :unnarrowed t)
          ("t" "topic" plain
           "* Definition\n\n* Key Points\n\n* Examples\n\n* Related Concepts\n"
           :target (file+head "topics/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: :topic:\n")
           :unnarrowed t))))
#+end_src

* Keybindings
** Org-Roam

Keybindings for org-roam note-taking.

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("r" . "roam")
       :desc "Find node"          "f" #'org-roam-node-find
       :desc "Insert node"        "i" #'org-roam-node-insert
       :desc "Capture to node"    "c" #'org-roam-capture
       :desc "Toggle roam buffer" "b" #'org-roam-buffer-toggle
       :desc "Open random note"   "r" #'org-roam-node-random))
#+end_src

* LaTeX
** Pure LaTeX Files

Configuration for writing `.tex` files with PDF preview.

#+begin_src emacs-lisp
(setq +latex-viewers '(pdf-tools)
      TeX-electric-sub-and-superscript t)
#+end_src

** Symbol Prettification

Show LaTeX symbols (like ∈, α, β) in the source buffer.

#+begin_src emacs-lisp
(add-hook! 'LaTeX-mode-hook #'prettify-symbols-mode)
#+end_src

** LaTeX Preview

Configuration for rendering LaTeX in org files.

Based on: https://abode.karthinks.com/org-latex-preview/

#+begin_src emacs-lisp
(use-package! org-latex-preview
  :after org
  :hook (org-mode . org-latex-preview-mode)
  :init
  (setq org-latex-preview-process-precompiled nil
        org-startup-with-latex-preview t)

  :config
  ;; Packages available during fragment compilation
  (after! org
    (dolist (pkg '("amsmath" "amssymb" "mathtools" "mathrsfs" "xcolor"))
      (add-to-list 'org-latex-packages-alist `("" ,pkg t))))

  ;; Appearance - increased vertical margin to prevent cutoff
  (plist-put org-latex-preview-appearance-options :page-width 1.0)
  (plist-put org-latex-preview-appearance-options :scale 1.5)
  (plist-put org-latex-preview-appearance-options :margin '(2 . 4))

  ;; Live preview behavior
  (setq org-latex-preview-mode-display-live t
        org-latex-preview-mode-update-delay 0.25
        org-latex-preview-mode-ignored-commands
        '(next-line previous-line mwheel-scroll ultra-scroll
          scroll-up-command scroll-down-command
          evil-scroll-up evil-scroll-down
          evil-scroll-line-up evil-scroll-line-down)))

;; Vertical alignment
(after! org-latex-preview
  (setq org-latex-preview-ascent 70))
#+end_src
